# Generated by Django 3.2.9 on 2022-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(default='admin', max_length=900),
        ),
        migrations.AddField(
            model_name='user',
            name='Country',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
