# Generated by Django 3.2.9 on 2022-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0002_auto_20220527_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
