# Generated by Django 3.2.9 on 2022-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0004_rename_profilepic_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
