# Generated by Django 3.2.9 on 2022-05-28 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0007_auto_20220527_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('ItemImage', models.ImageField(null=True, upload_to='images/')),
                ('ItemStatus', models.BooleanField(default=False)),
                ('Amount', models.IntegerField(default=0)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
