# Generated by Django 3.2.9 on 2022-05-29 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0008_auto_20220528_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='Benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefator', to=settings.AUTH_USER_MODEL),
        ),
    ]
