# Generated by Django 3.2.9 on 2022-06-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0009_create_benefactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='Owner',
            field=models.ForeignKey(limit_choices_to={'UserType': 'Donator'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Username',
            field=models.ForeignKey(limit_choices_to={'UserType': 'Receiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='users_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
