# Generated by Django 3.2.9 on 2022-06-02 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0010_auto_20220602_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='Benefactor',
            field=models.ForeignKey(limit_choices_to={'UserType': 'Receiver'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefator', to=settings.AUTH_USER_MODEL),
        ),
    ]
