# Generated by Django 3.2.9 on 2022-06-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earth', '0012_remove_create_itemstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='Amount',
        ),
    ]
